plan:
  global_plan_server:
    ros__parameters:
      expected_planner_frequency: 1.0
      use_sim_time: false
      planner_plugins: ["GridBased"]
      GridBased:
        plugin: "nav2_theta_star_planner/ThetaStarPlanner"
        how_many_corners: 8          # 4 / 8 邻域
        w_euc_cost: 1.0
        w_traversal_cost: 2.0
        w_heuristic_cost: 1.0
        publish_path: true
        publish_plan: true
  global_costmap:
    global_costmap:
      ros__parameters:
        global_frame: map
        robot_base_frame: base_link
        robot_radius: 0.25
        plugins: ["static_layer", "inflation_layer"]

        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          map_subscribe_transient_local: true
          map_topic: "/map/global_map"

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 0.3
          cost_scaling_factor: 3.0 